# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `dry-container` gem.
# Please instead update this file by running `bin/tapioca gem dry-container`.


# A collection of micro-libraries, each intended to encapsulate
# a common task in Ruby
#
# pkg:gem/dry-container#lib/dry/container/error.rb:3
module Dry; end

# Inversion of Control (IoC) container
#
# @example
#
#   container = Dry::Container.new
#   container.register(:item, 'item')
#   container.resolve(:item)
#   => 'item'
#
#   container.register(:item1, -> { 'item' })
#   container.resolve(:item1)
#   => 'item'
#
#   container.register(:item2, -> { 'item' }, call: false)
#   container.resolve(:item2)
#   => #<Proc:0x007f33b169e998@(irb):10 (lambda)>
#
# @api public
#
# pkg:gem/dry-container#lib/dry/container/error.rb:4
class Dry::Container
  include ::Dry::Container::Mixin::Initializer
  include ::Dry::Container::Mixin
  extend ::Dry::Container::Configuration

  # pkg:gem/dry-container#lib/dry/container.rb:33
  def config; end
end

# @api public
#
# pkg:gem/dry-container#lib/dry/container/mixin.rb:8
class Dry::Container::Config
  # @api private
  #
  # pkg:gem/dry-container#lib/dry/container/mixin.rb:23
  def initialize(namespace_separator: T.unsafe(nil), resolver: T.unsafe(nil), registry: T.unsafe(nil)); end

  # @api public
  #
  # pkg:gem/dry-container#lib/dry/container/mixin.rb:14
  def namespace_separator; end

  # @api public
  #
  # pkg:gem/dry-container#lib/dry/container/mixin.rb:14
  def namespace_separator=(_arg0); end

  # @api public
  #
  # pkg:gem/dry-container#lib/dry/container/mixin.rb:20
  def registry; end

  # @api public
  #
  # pkg:gem/dry-container#lib/dry/container/mixin.rb:20
  def registry=(_arg0); end

  # @api public
  #
  # pkg:gem/dry-container#lib/dry/container/mixin.rb:17
  def resolver; end

  # @api public
  #
  # pkg:gem/dry-container#lib/dry/container/mixin.rb:17
  def resolver=(_arg0); end
end

# pkg:gem/dry-container#lib/dry/container/mixin.rb:9
Dry::Container::Config::DEFAULT_NAMESPACE_SEPARATOR = T.let(T.unsafe(nil), String)

# pkg:gem/dry-container#lib/dry/container/mixin.rb:11
Dry::Container::Config::DEFAULT_REGISTRY = T.let(T.unsafe(nil), Dry::Container::Registry)

# pkg:gem/dry-container#lib/dry/container/mixin.rb:10
Dry::Container::Config::DEFAULT_RESOLVER = T.let(T.unsafe(nil), Dry::Container::Resolver)

# @api public
#
# pkg:gem/dry-container#lib/dry/container/mixin.rb:35
module Dry::Container::Configuration
  # @api private
  #
  # pkg:gem/dry-container#lib/dry/container/mixin.rb:53
  def config; end

  # @api private
  #
  # pkg:gem/dry-container#lib/dry/container/mixin.rb:59
  def configure; end
end

# pkg:gem/dry-container#lib/dry/container/mixin.rb:68
Dry::Container::EMPTY_HASH = T.let(T.unsafe(nil), Hash)

# @api public
#
# pkg:gem/dry-container#lib/dry/container/error.rb:6
class Dry::Container::Error < ::StandardError; end

# Base class to abstract Memoizable and Callable implementations
#
# @api abstract
#
# pkg:gem/dry-container#lib/dry/container/item.rb:9
class Dry::Container::Item
  # @api abstract
  #
  # pkg:gem/dry-container#lib/dry/container/item.rb:17
  def initialize(item, options = T.unsafe(nil)); end

  # @api abstract
  #
  # pkg:gem/dry-container#lib/dry/container/item.rb:25
  def call; end

  # @private
  #
  # pkg:gem/dry-container#lib/dry/container/item.rb:35
  def callable?; end

  # @return [Mixed] the item to be solved later
  #
  # pkg:gem/dry-container#lib/dry/container/item.rb:11
  def item; end

  # Build a new item with transformation applied
  #
  # @private
  #
  # pkg:gem/dry-container#lib/dry/container/item.rb:42
  def map(func); end

  # @return [Hash] the options to memoize, call or no.
  #
  # pkg:gem/dry-container#lib/dry/container/item.rb:14
  def options; end

  # @private
  #
  # pkg:gem/dry-container#lib/dry/container/item.rb:30
  def value?; end
end

# Callable class to returns a item call
#
# @api public
#
# pkg:gem/dry-container#lib/dry/container/item/callable.rb:12
class Dry::Container::Item::Callable < ::Dry::Container::Item
  # Returns the result of item call or item
  #
  # @return [Mixed]
  #
  # pkg:gem/dry-container#lib/dry/container/item/callable.rb:16
  def call; end
end

# Factory for create an Item to register inside of container
#
# @api public
#
# pkg:gem/dry-container#lib/dry/container/item/factory.rb:12
class Dry::Container::Item::Factory
  # Creates an Item Memoizable or Callable
  # @param [Mixed] item
  # @param [Hash] options
  #
  # @raise [Dry::Container::Error]
  #
  # @return [Dry::Container::Item::Base]
  #
  # pkg:gem/dry-container#lib/dry/container/item/factory.rb:20
  def call(item, options = T.unsafe(nil)); end
end

# Memoizable class to store and execute item calls
#
# @api public
#
# pkg:gem/dry-container#lib/dry/container/item/memoizable.rb:12
class Dry::Container::Item::Memoizable < ::Dry::Container::Item
  # Returns a new Memoizable instance
  #
  # @param [Mixed] item
  # @param [Hash] options
  #
  # @raise [Dry::Container::Error]
  #
  # @return [Dry::Container::Item::Base]
  #
  # pkg:gem/dry-container#lib/dry/container/item/memoizable.rb:24
  def initialize(item, options = T.unsafe(nil)); end

  # Returns the result of item call using a syncronized mutex
  #
  # @return [Dry::Container::Item::Base]
  #
  # pkg:gem/dry-container#lib/dry/container/item/memoizable.rb:34
  def call; end

  # @return [Mutex] the stored mutex
  #
  # pkg:gem/dry-container#lib/dry/container/item/memoizable.rb:14
  def memoize_mutex; end

  private

  # @private
  #
  # pkg:gem/dry-container#lib/dry/container/item/memoizable.rb:43
  def raise_not_supported_error; end
end

# pkg:gem/dry-container#lib/dry/container/error.rb:8
class Dry::Container::KeyError < ::KeyError; end

# Mixin to expose Inversion of Control (IoC) container behaviour
#
# @example
#
#   class MyClass
#     extend Dry::Container::Mixin
#   end
#
#   MyClass.register(:item, 'item')
#   MyClass.resolve(:item)
#   => 'item'
#
#   class MyObject
#     include Dry::Container::Mixin
#   end
#
#   container = MyObject.new
#   container.register(:item, 'item')
#   container.resolve(:item)
#   => 'item'
#
# @api public
#
# pkg:gem/dry-container#lib/dry/container/mixin.rb:94
module Dry::Container::Mixin
  mixes_in_class_methods ::Dry::Container::Configuration

  # Resolve an item from the container
  #
  # @param [Mixed] key
  #   The key for the item you wish to resolve
  #
  # @return [Mixed]
  #
  # @api public
  # @see Dry::Container::Mixin#resolve
  #
  # pkg:gem/dry-container#lib/dry/container/mixin.rb:187
  def [](key); end

  # @private no, really
  #
  # pkg:gem/dry-container#lib/dry/container/mixin.rb:331
  def _container; end

  # @api public
  #
  # pkg:gem/dry-container#lib/dry/container/mixin.rb:343
  def clone; end

  # Decorates an item from the container with specified decorator
  #
  # @return [Dry::Container::Mixin] self
  #
  # @api public
  #
  # pkg:gem/dry-container#lib/dry/container/mixin.rb:270
  def decorate(key, with: T.unsafe(nil), &block); end

  # @api public
  #
  # pkg:gem/dry-container#lib/dry/container/mixin.rb:336
  def dup; end

  # Calls block once for each key/value pair in the container, passing the key and
  # the registered item parameters.
  #
  # If no block is given, an enumerator is returned instead.
  #
  # @return [Enumerator]
  #
  # @api public
  #
  # @note In discussions with other developers, it was felt that being able to iterate
  #       over not just the registered keys, but to see what was registered would be
  #       very helpful. This is a step toward doing that.
  #
  # pkg:gem/dry-container#lib/dry/container/mixin.rb:261
  def each(&block); end

  # Calls block once for each key in container, passing the key as a parameter.
  #
  # If no block is given, an enumerator is returned instead.
  #
  # @return [Dry::Container::Mixin] self
  #
  # @api public
  #
  # pkg:gem/dry-container#lib/dry/container/mixin.rb:244
  def each_key(&block); end

  # Freeze the container. Nothing can be registered after freezing
  #
  # @api public
  #
  # pkg:gem/dry-container#lib/dry/container/mixin.rb:324
  def freeze; end

  # Import a namespace
  #
  # @param [Dry::Container::Namespace] namespace
  #   The namespace to import
  #
  # @return [Dry::Container::Mixin] self
  #
  # @api public
  #
  # pkg:gem/dry-container#lib/dry/container/mixin.rb:315
  def import(namespace); end

  # Check whether an item is registered under the given key
  #
  # @param [Mixed] key
  #   The key you wish to check for registration with
  #
  # @return [Bool]
  #
  # @api public
  #
  # pkg:gem/dry-container#lib/dry/container/mixin.rb:224
  def key?(key); end

  # An array of registered names for the container
  #
  # @return [Array<String>]
  #
  # @api public
  #
  # pkg:gem/dry-container#lib/dry/container/mixin.rb:233
  def keys; end

  # Merge in the items of the other container
  #
  # @param [Dry::Container] other
  #   The other container to merge in
  # @param [Symbol, nil] namespace
  #   Namespace to prefix other container items with, defaults to nil
  #
  # @return [Dry::Container::Mixin] self
  #
  # @api public
  #
  # pkg:gem/dry-container#lib/dry/container/mixin.rb:201
  def merge(other, namespace: T.unsafe(nil), &block); end

  # Evaluate block and register items in namespace
  #
  # @param [Mixed] namespace
  #   The namespace to register items in
  #
  # @return [Dry::Container::Mixin] self
  #
  # @api public
  #
  # pkg:gem/dry-container#lib/dry/container/mixin.rb:296
  def namespace(namespace, &block); end

  # Register an item with the container to be resolved later
  #
  # @param [Mixed] key
  #   The key to register the container item with (used to resolve)
  # @param [Mixed] contents
  #   The item to register with the container (if no block given)
  # @param [Hash] options
  #   Options to pass to the registry when registering the item
  # @yield
  #   If a block is given, contents will be ignored and the block
  #   will be registered instead
  #
  # @return [Dry::Container::Mixin] self
  #
  # @api public
  #
  # pkg:gem/dry-container#lib/dry/container/mixin.rb:147
  def register(key, contents = T.unsafe(nil), options = T.unsafe(nil), &block); end

  # Resolve an item from the container
  #
  # @param [Mixed] key
  #   The key for the item you wish to resolve
  # @yield
  #   Fallback block to call when a key is missing. Its result will be returned
  # @yieldparam [Mixed] key Missing key
  #
  # @return [Mixed]
  #
  # @api public
  #
  # pkg:gem/dry-container#lib/dry/container/mixin.rb:174
  def resolve(key, &block); end

  class << self
    # @private
    #
    # pkg:gem/dry-container#lib/dry/container/mixin.rb:96
    def extended(base); end

    # @private
    #
    # pkg:gem/dry-container#lib/dry/container/mixin.rb:121
    def included(base); end
  end
end

# @private
#
# pkg:gem/dry-container#lib/dry/container/mixin.rb:113
module Dry::Container::Mixin::Initializer
  # pkg:gem/dry-container#lib/dry/container/mixin.rb:114
  def initialize(*args, &block); end
end

# Create a namespace to be imported
#
# @example
#
#   ns = Dry::Container::Namespace.new('name') do
#     register('item', 'item')
#   end
#
#   container = Dry::Container.new
#
#   container.import(ns)
#
#   container.resolve('name.item')
#   => 'item'
#
#
# @api public
#
# pkg:gem/dry-container#lib/dry/container/namespace.rb:22
class Dry::Container::Namespace
  # Create a new namespace
  #
  # @param [Mixed] name
  #   The name of the namespace
  # @yield
  #   The block to evaluate when the namespace is imported
  #
  # @return [Dry::Container::Namespace]
  #
  # @api public
  #
  # pkg:gem/dry-container#lib/dry/container/namespace.rb:38
  def initialize(name, &block); end

  # @return [Proc] The block to be executed when the namespace is imported
  #
  # pkg:gem/dry-container#lib/dry/container/namespace.rb:26
  def block; end

  # @return [Mixed] The namespace (name)
  #
  # pkg:gem/dry-container#lib/dry/container/namespace.rb:24
  def name; end
end

# @api private
#
# pkg:gem/dry-container#lib/dry/container/namespace_dsl.rb:8
class Dry::Container::NamespaceDSL < ::SimpleDelegator
  # DSL for defining namespaces
  #
  # @param [Dry::Container::Mixin] container
  #   The container
  # @param [String] namespace
  #   The namespace (name)
  # @param [String] namespace_separator
  #   The namespace separator
  # @yield
  #   The block to evaluate to define the namespace
  #
  # @return [Mixed]
  #
  # @api private
  #
  # pkg:gem/dry-container#lib/dry/container/namespace_dsl.rb:23
  def initialize(container, namespace, namespace_separator, &block); end

  # pkg:gem/dry-container#lib/dry/container/namespace_dsl.rb:44
  def import(namespace); end

  # pkg:gem/dry-container#lib/dry/container/namespace_dsl.rb:40
  def namespace(namespace, &block); end

  # pkg:gem/dry-container#lib/dry/container/namespace_dsl.rb:36
  def register(key, *args, &block); end

  # pkg:gem/dry-container#lib/dry/container/namespace_dsl.rb:50
  def resolve(key); end

  private

  # pkg:gem/dry-container#lib/dry/container/namespace_dsl.rb:56
  def namespaced(key); end
end

# pkg:gem/dry-container#lib/dry/container/mixin.rb:64
Dry::Container::PREFIX_NAMESPACE = T.let(T.unsafe(nil), Proc)

# Default registry for registering items with the container
#
# @api public
#
# pkg:gem/dry-container#lib/dry/container/registry.rb:10
class Dry::Container::Registry
  # @private
  #
  # pkg:gem/dry-container#lib/dry/container/registry.rb:12
  def initialize; end

  # Register an item with the container to be resolved later
  #
  # @param [Concurrent::Hash] container
  #   The container
  # @param [Mixed] key
  #   The key to register the container item with (used to resolve)
  # @param [Mixed] item
  #   The item to register with the container
  # @param [Hash] options
  # @option options [Symbol] :call
  #   Whether the item should be called when resolved
  #
  # @raise [Dry::Container::Error]
  #   If an item is already registered with the given key
  #
  # @return [Mixed]
  #
  # @api public
  #
  # pkg:gem/dry-container#lib/dry/container/registry.rb:34
  def call(container, key, item, options); end

  # pkg:gem/dry-container#lib/dry/container/registry.rb:45
  def factory; end
end

# Default resolver for resolving items from container
#
# @api public
#
# pkg:gem/dry-container#lib/dry/container/resolver.rb:8
class Dry::Container::Resolver
  # Resolve an item from the container
  #
  # @param [Concurrent::Hash] container
  #   The container
  # @param [Mixed] key
  #   The key for the item you wish to resolve
  # @yield
  #   Fallback block to call when a key is missing. Its result will be returned
  # @yieldparam [Mixed] key Missing key
  #
  # @raise [KeyError]
  #   If the given key is not registered with the container (and no block provided)
  #
  #
  # @return [Mixed]
  #
  # @api public
  #
  # pkg:gem/dry-container#lib/dry/container/resolver.rb:26
  def call(container, key); end

  # Calls block once for each key in container, passing the key and
  # the registered item parameters.
  #
  # If no block is given, an enumerator is returned instead.
  #
  # @return Key, Value
  #
  # @api public
  # @note In discussions with other developers, it was felt that being able
  #       to iterate over not just the registered keys, but to see what was
  #       registered would be very helpful. This is a step toward doing that.
  #
  # pkg:gem/dry-container#lib/dry/container/resolver.rb:83
  def each(container, &block); end

  # Calls block once for each key in container, passing the key as a parameter.
  #
  # If no block is given, an enumerator is returned instead.
  #
  # @return Hash
  #
  # @api public
  #
  # pkg:gem/dry-container#lib/dry/container/resolver.rb:68
  def each_key(container, &block); end

  # Check whether an items is registered under the given key
  #
  # @param [Concurrent::Hash] container
  #   The container
  # @param [Mixed] key
  #   The key you wish to check for registration with
  #
  # @return [Bool]
  #
  # @api public
  #
  # pkg:gem/dry-container#lib/dry/container/resolver.rb:48
  def key?(container, key); end

  # An array of registered names for the container
  #
  # @return [Array]
  #
  # @api public
  #
  # pkg:gem/dry-container#lib/dry/container/resolver.rb:57
  def keys(container); end
end

# @api public
#
# pkg:gem/dry-container#lib/dry/container/version.rb:6
Dry::Container::VERSION = T.let(T.unsafe(nil), String)
